name: "Composite Action for Caching Corpus"
description: "Caches corpus directory"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: corpus
        key: corpus-${{ hashFiles('corpus/**') }}
